<a href="https://colab.research.google.com/github/Kaustavee/DataVista-_Sales-_Data-_Analysis-_and-_Visualization_Infosys-Internship-2025/blob/main/Pandas_%26_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PANDAS**

In [ ]:
import pandas as pd
df = pd.read_csv('/content/pokemon_data.csv')

In [ ]:
df.head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [ ]:
df.head(3)
df.head(10)

#                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1                  Bulbasaur  Grass  Poison  45      49       49       65   
1  2                    Ivysaur  Grass  Poison  60      62       63       80   
2  3                   Venusaur  Grass  Poison  80      82       83      100   
3  3      VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4                 Charmander   Fire     NaN  39      52       43       60   
5  5                 Charmeleon   Fire     NaN  58      64       58       80   
6  6                  Charizard   Fire  Flying  78      84       78      109   
7  6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130   
8  6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159   
9  7                   Squirtle  Water     NaN  44      48       65       50   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False  
5       65     80           1      False  
6       85    100           1      False  
7       85    100           1      False  
8      115    100           1      False  
9       64     43           1      False

In [ ]:
df.tail()

#                 Name   Type 1 Type 2  HP  Attack  Defense  Sp. Atk  \
795  719              Diancie     Rock  Fairy  50     100      150      100   
796  719  DiancieMega Diancie     Rock  Fairy  50     160      110      160   
797  720  HoopaHoopa Confined  Psychic  Ghost  80     110       60      150   
798  720   HoopaHoopa Unbound  Psychic   Dark  80     160       60      170   
799  721            Volcanion     Fire  Water  80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
795      150     50           6       True  
796      110    110           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True

In [ ]:
df_excel = pd.read_excel('/content/pokemon_data.xlsx')
df_excel.head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [ ]:
df_txt = pd.read_csv('/content/pokemon_data.txt', delimiter='\t')
df_txt.head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [ ]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [ ]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [ ]:
df.shape

(800, 12)

In [ ]:
df.Name

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [ ]:
df.isna()

#   Name  Type 1  Type 2     HP  Attack  Defense  Sp. Atk  Sp. Def  \
0    False  False   False   False  False   False    False    False    False   
1    False  False   False   False  False   False    False    False    False   
2    False  False   False   False  False   False    False    False    False   
3    False  False   False   False  False   False    False    False    False   
4    False  False   False    True  False   False    False    False    False   
..     ...    ...     ...     ...    ...     ...      ...      ...      ...   
795  False  False   False   False  False   False    False    False    False   
796  False  False   False   False  False   False    False    False    False   
797  False  False   False   False  False   False    False    False    False   
798  False  False   False   False  False   False    False    False    False   
799  False  False   False   False  False   False    False    False    False   

     Speed  Generation  Legendary  
0    False       False      False  
1    False       False      False  
2    False       False      False  
3    False       False      False  
4    False       False      False  
..     ...         ...        ...  
795  False       False      False  
796  False       False      False  
797  False       False      False  
798  False       False      False  
799  False       False      False  

[800 rows x 12 columns]

In [ ]:
df.isna().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
df.isnull()

#   Name  Type 1  Type 2     HP  Attack  Defense  Sp. Atk  Sp. Def  \
0    False  False   False   False  False   False    False    False    False   
1    False  False   False   False  False   False    False    False    False   
2    False  False   False   False  False   False    False    False    False   
3    False  False   False   False  False   False    False    False    False   
4    False  False   False    True  False   False    False    False    False   
..     ...    ...     ...     ...    ...     ...      ...      ...      ...   
795  False  False   False   False  False   False    False    False    False   
796  False  False   False   False  False   False    False    False    False   
797  False  False   False   False  False   False    False    False    False   
798  False  False   False   False  False   False    False    False    False   
799  False  False   False   False  False   False    False    False    False   

     Speed  Generation  Legendary  
0    False       False      False  
1    False       False      False  
2    False       False      False  
3    False       False      False  
4    False       False      False  
..     ...         ...        ...  
795  False       False      False  
796  False       False      False  
797  False       False      False  
798  False       False      False  
799  False       False      False  

[800 rows x 12 columns]

In [ ]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [ ]:
df[['Name','Type 1','HP']]

Name   Type 1  HP
0                Bulbasaur    Grass  45
1                  Ivysaur    Grass  60
2                 Venusaur    Grass  80
3    VenusaurMega Venusaur    Grass  80
4               Charmander     Fire  39
..                     ...      ...  ..
795                Diancie     Rock  50
796    DiancieMega Diancie     Rock  50
797    HoopaHoopa Confined  Psychic  80
798     HoopaHoopa Unbound  Psychic  80
799              Volcanion     Fire  80

[800 rows x 3 columns]

In [ ]:
df.iloc[1:4]

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   

   Sp. Def  Speed  Generation  Legendary  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False

In [ ]:
df.loc[1:4]

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False

In [ ]:
df.iloc[2,4]
print(df.iloc[2,4])

80


In [ ]:
for index, row in df.iterrows():
  print(index, row['Name'])

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur
4 Charmander
5 Charmeleon
6 Charizard
7 CharizardMega Charizard X
8 CharizardMega Charizard Y
9 Squirtle
10 Wartortle
11 Blastoise
12 BlastoiseMega Blastoise
13 Caterpie
14 Metapod
15 Butterfree
16 Weedle
17 Kakuna
18 Beedrill
19 BeedrillMega Beedrill
20 Pidgey
21 Pidgeotto
22 Pidgeot
23 PidgeotMega Pidgeot
24 Rattata
25 Raticate
26 Spearow
27 Fearow
28 Ekans
29 Arbok
30 Pikachu
31 Raichu
32 Sandshrew
33 Sandslash
34 Nidoran (Female)
35 Nidorina
36 Nidoqueen
37 Nidoran (Male)
38 Nidorino
39 Nidoking
40 Clefairy
41 Clefable
42 Vulpix
43 Ninetales
44 Jigglypuff
45 Wigglytuff
46 Zubat
47 Golbat
48 Oddish
49 Gloom
50 Vileplume
51 Paras
52 Parasect
53 Venonat
54 Venomoth
55 Diglett
56 Dugtrio
57 Meowth
58 Persian
59 Psyduck
60 Golduck
61 Mankey
62 Primeape
63 Growlithe
64 Arcanine
65 Poliwag
66 Poliwhirl
67 Poliwrath
68 Abra
69 Kadabra
70 Alakazam
71 AlakazamMega Alakazam
72 Machop
73 Machoke
74 Machamp
75 Bellsprout
76 Weepinbell
77 

In [ ]:
print(df.loc[df['Type 1']=='Fire'])

       #                       Name Type 1    Type 2   HP  Attack  Defense  \
4      4                 Charmander   Fire       NaN   39      52       43   
5      5                 Charmeleon   Fire       NaN   58      64       58   
6      6                  Charizard   Fire    Flying   78      84       78   
7      6  CharizardMega Charizard X   Fire    Dragon   78     130      111   
8      6  CharizardMega Charizard Y   Fire    Flying   78     104       78   
42    37                     Vulpix   Fire       NaN   38      41       40   
43    38                  Ninetales   Fire       NaN   73      76       75   
63    58                  Growlithe   Fire       NaN   55      70       45   
64    59                   Arcanine   Fire       NaN   90     110       80   
83    77                     Ponyta   Fire       NaN   50      85       55   
84    78                   Rapidash   Fire       NaN   65     100       70   
135  126                     Magmar   Fire       NaN   65      9

In [ ]:
df.describe()

#          HP      Attack     Defense     Sp. Atk     Sp. Def  \
count  800.000000  800.000000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750   69.258750   79.001250   73.842500   72.820000   71.902500   
std    208.343798   25.534669   32.457366   31.183501   32.722294   27.828916   
min      1.000000    1.000000    5.000000    5.000000   10.000000   20.000000   
25%    184.750000   50.000000   55.000000   50.000000   49.750000   50.000000   
50%    364.500000   65.000000   75.000000   70.000000   65.000000   70.000000   
75%    539.250000   80.000000  100.000000   90.000000   95.000000   90.000000   
max    721.000000  255.000000  190.000000  230.000000  194.000000  230.000000   

            Speed  Generation  
count  800.000000   800.00000  
mean    68.277500     3.32375  
std     29.060474     1.66129  
min      5.000000     1.00000  
25%     45.000000     2.00000  
50%     65.000000     3.00000  
75%     90.000000     5.00000  
max    180.000000     6.00000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   #           800 non-null    int64 
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64 
 5   Attack      800 non-null    int64 
 6   Defense     800 non-null    int64 
 7   Sp. Atk     800 non-null    int64 
 8   Sp. Def     800 non-null    int64 
 9   Speed       800 non-null    int64 
 10  Generation  800 non-null    int64 
 11  Legendary   800 non-null    bool  
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB


In [ ]:
df.sort_values('Name')

#                     Name   Type 1  Type 2   HP  Attack  Defense  \
510  460                Abomasnow    Grass     Ice   90      92       75   
511  460  AbomasnowMega Abomasnow    Grass     Ice   90     132      105   
68    63                     Abra  Psychic     NaN   25      20       15   
392  359                    Absol     Dark     NaN   65     130       60   
393  359          AbsolMega Absol     Dark     NaN   65     150       60   
..   ...                      ...      ...     ...  ...     ...      ...   
632  571                  Zoroark     Dark     NaN   60     105       60   
631  570                    Zorua     Dark     NaN   40      65       40   
46    41                    Zubat   Poison  Flying   40      45       35   
695  634                 Zweilous     Dark  Dragon   72      85       70   
794  718         Zygarde50% Forme   Dragon  Ground  108     100      121   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
510       92       85     60           4      False  
511      132      105     30           4      False  
68       105       55     90           1      False  
392       75       60     75           3      False  
393      115       60    115           3      False  
..       ...      ...    ...         ...        ...  
632      120       60    105           5      False  
631       80       40     65           5      False  
46        30       40     55           1      False  
695       65       70     58           5      False  
794       81       95     95           6       True  

[800 rows x 12 columns]

In [ ]:
df.sort_values('Name', ascending=False)

#                     Name   Type 1  Type 2   HP  Attack  Defense  \
794  718         Zygarde50% Forme   Dragon  Ground  108     100      121   
695  634                 Zweilous     Dark  Dragon   72      85       70   
46    41                    Zubat   Poison  Flying   40      45       35   
631  570                    Zorua     Dark     NaN   40      65       40   
632  571                  Zoroark     Dark     NaN   60     105       60   
..   ...                      ...      ...     ...  ...     ...      ...   
393  359          AbsolMega Absol     Dark     NaN   65     150       60   
392  359                    Absol     Dark     NaN   65     130       60   
68    63                     Abra  Psychic     NaN   25      20       15   
511  460  AbomasnowMega Abomasnow    Grass     Ice   90     132      105   
510  460                Abomasnow    Grass     Ice   90      92       75   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
794       81       95     95           6       True  
695       65       70     58           5      False  
46        30       40     55           1      False  
631       80       40     65           5      False  
632      120       60    105           5      False  
..       ...      ...    ...         ...        ...  
393      115       60    115           3      False  
392       75       60     75           3      False  
68       105       55     90           1      False  
511      132      105     30           4      False  
510       92       85     60           4      False  

[800 rows x 12 columns]

In [ ]:
df.sort_values(['Type 1','HP'], ascending=[1,0])

#                     Name Type 1    Type 2  HP  Attack  Defense  \
520  469                  Yanmega    Bug    Flying  86      76       86   
698  637                Volcarona    Bug      Fire  85      60       65   
231  214                Heracross    Bug  Fighting  80     125       75   
232  214  HeracrossMega Heracross    Bug  Fighting  80     185      115   
678  617                 Accelgor    Bug       NaN  80      70       40   
..   ...                      ...    ...       ...  ..     ...      ...   
106   98                   Krabby  Water       NaN  30     105       90   
125  116                   Horsea  Water       NaN  30      40       70   
129  120                   Staryu  Water       NaN  30      45       55   
139  129                 Magikarp  Water       NaN  20      10       55   
381  349                   Feebas  Water       NaN  20      15       20   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
520      116       56     95           4      False  
698      135      105    100           5      False  
231       40       95     85           2      False  
232       40      105     75           2      False  
678      100       60    145           5      False  
..       ...      ...    ...         ...        ...  
106       25       25     50           1      False  
125       70       25     60           1      False  
129       70       55     85           1      False  
139       15       20     80           1      False  
381       10       55     80           3      False  

[800 rows x 12 columns]

In [ ]:
df['Total Points'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

In [ ]:
print(df.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  Total Points  
0       65     45           1      False           318  
1       80     60           1      False           405  
2      100     80           1      False           525  
3      120     80           1      False           625  
4       50     65           1       True           309  


In [ ]:
df.drop(columns=['Total Points'])

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1       True  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [ ]:
df['Total Points'] = df.iloc[:,4:10].sum(axis=1)

In [ ]:
df.head()

#                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  Total Points  
0       65     45           1      False           318  
1       80     60           1      False           405  
2      100     80           1      False           525  
3      120     80           1      False           625  
4       50     65           1       True           309

In [ ]:
cols = list(df.columns.values)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]
df.head()

#                   Name Type 1  Type 2  Total Points  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison           318  45      49       49   
1  2                Ivysaur  Grass  Poison           405  60      62       63   
2  3               Venusaur  Grass  Poison           525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison           625  80     100      123   
4  4             Charmander   Fire     NaN           309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1       True

In [ ]:
df.to_csv('modified.csv', index=False)

# **NUMPY**

In [ ]:
import numpy as np

In [ ]:
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)
print(f"NumPy array from list: {numpy_array}")
print(f"Type of numpy_array: {type(numpy_array)}")
print(f"Data type of elements: {numpy_array.dtype}")

NumPy array from list: [1 2 3 4 5]
Type of numpy_array: <class 'numpy.ndarray'>
Data type of elements: int64


In [ ]:
python_nested_list = [[1, 2, 3], [4, 5, 6]]
numpy_2d_array = np.array(python_nested_list)
print(f"\nNumPy 2D array from nested list:\n{numpy_2d_array}")
print(f"Shape of numpy_2d_array: {numpy_2d_array.shape}")


NumPy 2D array from nested list:
[[1 2 3]
 [4 5 6]]
Shape of numpy_2d_array: (2, 3)


In [ ]:
arange_array = np.arange(0, 10, 2)
print(f"\nArray using np.arange(): {arange_array}")


Array using np.arange(): [0 2 4 6 8]


In [ ]:
zeros_array = np.zeros((3, 4))
print(f"\nArray of zeros:\n{zeros_array}")


Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones_array = np.ones((2, 3), dtype=int)
print(f"\nArray of ones:\n{ones_array}")


Array of ones:
[[1 1 1]
 [1 1 1]]


In [ ]:
linspace_array = np.linspace(0, 1, 5) # Start, Stop (inclusive), Number of elements
print(f"\nArray using np.linspace(): {linspace_array}")



Array using np.linspace(): [0.   0.25 0.5  0.75 1.  ]


In [ ]:
rand_array = np.random.rand(2, 2)
print(f"\nArray with random values (0-1):\n{rand_array}")


Array with random values (0-1):
[[0.00788122 0.12430245]
 [0.50000514 0.2894136 ]]


In [ ]:
randn_array = np.random.randn(3)
print(f"\nArray with random values (normal distribution):\n{randn_array}")


Array with random values (normal distribution):
[0.13660186 0.44099713 1.61183197]


In [ ]:
randint_array = np.random.randint(1, 10, size=(2, 4)) # Low, High (exclusive), Shape
print(f"\nArray with random integers:\n{randint_array}")


Array with random integers:
[[4 4 7 7]
 [7 4 7 2]]


In [ ]:

array1 = np.array([10, 20, 30, 40])
array2 = np.array([2, 3, 4, 5])

In [ ]:
# Element-wise operations
print(f"\nArray 1: {array1}")
print(f"Array 2: {array2}")
print(f"Addition: {array1 + array2}")
print(f"Subtraction: {array1 - array2}")
print(f"Multiplication: {array1 * array2}")
print(f"Division: {array1 / array2}")
print(f"Exponentiation: {array1 ** 2}")


Array 1: [10 20 30 40]
Array 2: [2 3 4 5]
Addition: [12 23 34 45]
Subtraction: [ 8 17 26 35]
Multiplication: [ 20  60 120 200]
Division: [5.         6.66666667 7.5        8.        ]
Exponentiation: [ 100  400  900 1600]


In [ ]:
# Scalar operations (applied to each element)
print(f"\nArray 1 multiplied by 10: {array1 * 10}")
print(f"Array 1 plus 5: {array1 + 5}")


Array 1 multiplied by 10: [100 200 300 400]
Array 1 plus 5: [15 25 35 45]


In [ ]:
print(f"\nArray 1 > 25: {array1 > 25}")
print(f"Array 1 == Array 2: {array1 == array2}")


Array 1 > 25: [False False  True  True]
Array 1 == Array 2: [False False False False]


In [ ]:
my_array = np.arange(10)
print(f"\nMy array: {my_array}")


My array: [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Accessing single elements
print(f"Element at index 0: {my_array[0]}")
print(f"Element at index -1 (last element): {my_array[-1]}")

# Slicing (start:stop:step)
print(f"Elements from index 2 to 5 (exclusive): {my_array[2:5]}")
print(f"Elements from the beginning to index 7 (exclusive): {my_array[:7]}")
print(f"Elements from index 3 to the end: {my_array[3:]}")
print(f"Every other element: {my_array[::2]}")

# Indexing and slicing in 2D arrays
my_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nMy 2D array:\n{my_2d_array}")


Element at index 0: 0
Element at index -1 (last element): 9
Elements from index 2 to 5 (exclusive): [2 3 4]
Elements from the beginning to index 7 (exclusive): [0 1 2 3 4 5 6]
Elements from index 3 to the end: [3 4 5 6 7 8 9]
Every other element: [0 2 4 6 8]

My 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Accessing single element: [row_index, column_index]
print(f"Element at row 0, column 1: {my_2d_array[0, 1]}")

# Slicing rows
print(f"First row: {my_2d_array[0, :]}")
print(f"First two rows:\n{my_2d_array[:2, :]}")

# Slicing columns
print(f"First column: {my_2d_array[:, 0]}")
print(f"First two columns:\n{my_2d_array[:, :2]}")

# Sub-matrix
print(f"Top-left 2x2 sub-matrix:\n{my_2d_array[:2, :2]}")

Element at row 0, column 1: 2
First row: [1 2 3]
First two rows:
[[1 2 3]
 [4 5 6]]
First column: [1 4 7]
First two columns:
[[1 2]
 [4 5]
 [7 8]]
Top-left 2x2 sub-matrix:
[[1 2]
 [4 5]]


In [ ]:
# ## Statistical Functions

data = np.array([2, 5, 1, 8, 3, 9, 4, 7, 6])
print(f"\nData array: {data}")

# **Mean:** Average of all elements
mean_value = np.mean(data)
print(f"Mean: {mean_value}")

# **Median:** Middle value when the data is sorted
median_value = np.median(data)
print(f"Median: {median_value}")


Data array: [2 5 1 8 3 9 4 7 6]
Mean: 5.0
Median: 5.0


In [ ]:
# **Standard Deviation:** Measure of the dispersion of a set of values
std_dev = np.std(data)
print(f"Standard Deviation: {std_dev}")

# **Variance:** Square of the standard deviation
variance = np.var(data)
print(f"Variance: {variance}")

# **Minimum and Maximum:**
min_value = np.min(data)
max_value = np.max(data)
print(f"Minimum: {min_value}")
print(f"Maximum: {max_value}")

Standard Deviation: 2.581988897471611
Variance: 6.666666666666667
Minimum: 1
Maximum: 9
